/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista;

import javax.swing.JLabel;

/**
 *
 * @author Estudiantes
 */
public class PantallaCuotas extends javax.swing.JFrame {

    double prestamo, interes;
    int plazo;
    
    public PantallaCuotas(double prestamo, float interes, int plazo) {
        initComponents();
        this.setLocationRelativeTo(null);
        
        this.prestamo = prestamo;
        this.interes = interes;
        this.plazo = plazo;
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Cuotas");

        jPanel1.setLayout(new java.awt.GridLayout(0, 5));
        jScrollPane1.setViewportView(jPanel1);

        jButton1.setText("Regresar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(240, 240, 240))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        mostrar();
    }//GEN-LAST:event_formWindowActivated

    public void mostrar(){
        double cuota = prestamo/plazo;
        JLabel label;
        double[][] matriz = new double[plazo][5];
        matriz[0][0] = 0;
        matriz[0][1] = 0;
        matriz[0][2] = 0;
        matriz[0][3] = 0;
        matriz[0][4] = prestamo;
        for (int i = 1; i < plazo+1; i++) {
            for (int j = 0; j < 5; j++) {
                if(j==0){
                    matriz[i][j] = i;
                }
                if(j==1){
                    matriz[i][j]=cuota;
                }
                if(j==2){
                    matriz[i][j] = matriz[i-1][4]*(interes/100);
                }
                if(j==3){
                    matriz[i][j]= matriz[i][2]+cuota;
                }
                if(j==4){
                    matriz[i][j]=  matriz[i-1][4] - cuota;
                }
            }
        }
        String[] c = {"Mes","Cuota","Interes","Amortizativo","Capital"};
        for (int i = 0; i < 5; i++) {
            label = new JLabel();
                label.setSize(110, 30);
                label.setText(c[i]);
                jPanel1.add(label);
        }
        jPanel1.updateUI();
        for (int i = 0; i < plazo; i++) {
            for (int j = 0; j < 5; j++) {
                label = new JLabel();
                label.setSize(110, 30);
                label.setText(matriz[i][j]+"");
                jPanel1.add(label);
            }
            
        }
        jPanel1.updateUI();  
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
