package ec.edu.ups.vista;

import ec.edu.ups.controlador.ControladorCurso;
import ec.edu.ups.controlador.ControladorPersona;
import ec.edu.ups.modelo.Curso;
import ec.edu.ups.modelo.Persona;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sebastian Uyaguari
 */
public class PantallaGestionRector extends javax.swing.JFrame {

    ControladorPersona controladorPersona;
    ControladorCurso controladorCurso;
    
    PantallaRegistroPersona pantallaRegistroPersona;
    PantallaEditarPersona pantallaEditarPersona;
    PantallaPrincipal pantallaPrincipal;
    PantallaRegistroCurso pantallaRegistroCurso;
    PantallaEditarCurso pantallaEditarCurso;
    
    Persona rector;
    Persona editar;
    
    Curso editarCurso;
    /**
     * Creates new form PantallaGestionRector
     */
    public PantallaGestionRector(Persona rector) {
        initComponents();
        this.setLocationRelativeTo(null);
        
        controladorPersona = ControladorPersona.getInstance();
        controladorCurso = ControladorCurso.getInstance();
        
        pantallaRegistroPersona = new PantallaRegistroPersona("Docente");
        pantallaPrincipal = new PantallaPrincipal();
        pantallaRegistroCurso = new PantallaRegistroCurso();
        
        this.rector = rector;
        
        cargarDatos();
        desactivarBotonesDocente();
        desactivarBotonesCurso();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnCrearDocente = new javax.swing.JButton();
        btnActualizarDocente = new javax.swing.JButton();
        btnListarDocentes = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDocente = new javax.swing.JTable();
        btnCancelarDocente = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtDirector = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btnCrearCursos = new javax.swing.JButton();
        btnActualizarCursos = new javax.swing.JButton();
        btnListarCursos = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCursos = new javax.swing.JTable();
        btnCancelarCurso = new javax.swing.JButton();
        btnCerrarSesion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestion Rector");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Gestion Cursos y Docentes");

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Gestion Docente");

        btnCrearDocente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagen/anadir.png"))); // NOI18N
        btnCrearDocente.setText("Crear");
        btnCrearDocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearDocenteActionPerformed(evt);
            }
        });

        btnActualizarDocente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagen/editar.png"))); // NOI18N
        btnActualizarDocente.setText("Actualizar");
        btnActualizarDocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarDocenteActionPerformed(evt);
            }
        });

        btnListarDocentes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagen/lista.png"))); // NOI18N
        btnListarDocentes.setText("Listar");
        btnListarDocentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarDocentesActionPerformed(evt);
            }
        });

        tblDocente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Rol", "Nombre", "Apellido", "Cedula"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDocente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDocenteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDocente);

        btnCancelarDocente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagen/cancelar.png"))); // NOI18N
        btnCancelarDocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarDocenteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnCrearDocente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnListarDocentes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnActualizarDocente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCancelarDocente, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 128, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(121, 121, 121))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancelarDocente, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnCrearDocente)
                        .addComponent(btnListarDocentes)
                        .addComponent(btnActualizarDocente)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel3.setText("Director:");

        txtDirector.setEditable(false);

        jLabel4.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel4.setText("Cedula:");

        txtCedula.setEditable(false);

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Gestion Cursos");

        btnCrearCursos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagen/anadir.png"))); // NOI18N
        btnCrearCursos.setText("Crear");
        btnCrearCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearCursosActionPerformed(evt);
            }
        });

        btnActualizarCursos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagen/editar.png"))); // NOI18N
        btnActualizarCursos.setText("Actualizar");
        btnActualizarCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarCursosActionPerformed(evt);
            }
        });

        btnListarCursos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagen/lista.png"))); // NOI18N
        btnListarCursos.setText("Listar");
        btnListarCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarCursosActionPerformed(evt);
            }
        });

        tblCursos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Curso", "Numero de Alumnos", "Docente"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCursos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCursosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblCursos);

        btnCancelarCurso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagen/cancelar.png"))); // NOI18N
        btnCancelarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarCursoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnCrearCursos)
                        .addGap(10, 10, 10)
                        .addComponent(btnListarCursos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnActualizarCursos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelarCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCrearCursos)
                            .addComponent(btnActualizarCursos)
                            .addComponent(btnListarCursos))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnCancelarCurso))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagen/logout.png"))); // NOI18N
        btnCerrarSesion.setText("Cerrar Sesion");
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDirector, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCerrarSesion)
                                .addContainerGap())))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnCerrarSesion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDirector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearDocenteActionPerformed
        pantallaRegistroPersona.setVisible(true);
        listarDocentes();
    }//GEN-LAST:event_btnCrearDocenteActionPerformed

    private void btnListarDocentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarDocentesActionPerformed
        listarDocentes();
    }//GEN-LAST:event_btnListarDocentesActionPerformed

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        this.dispose();
        limpiar();
        pantallaPrincipal.setVisible(true);
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void btnActualizarDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarDocenteActionPerformed
        pantallaEditarPersona = new PantallaEditarPersona(editar);
        pantallaEditarPersona.setVisible(true);
        tblDocente.clearSelection();
        desactivarBotonesDocente();
    }//GEN-LAST:event_btnActualizarDocenteActionPerformed

    private void tblDocenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDocenteMouseClicked
        int pos = tblDocente.getSelectedRow();
        
        String cedula = (String) tblDocente.getValueAt(pos, 3);
        
        editar = controladorPersona.read(new Persona(0, "", cedula, "", "", "", ""));
        
        activarBotonesDocente();
    }//GEN-LAST:event_tblDocenteMouseClicked

    private void btnCancelarDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarDocenteActionPerformed
        desactivarBotonesDocente();
    }//GEN-LAST:event_btnCancelarDocenteActionPerformed

    private void btnCrearCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearCursosActionPerformed
        pantallaRegistroCurso.setVisible(true);
        listarCursos();
    }//GEN-LAST:event_btnCrearCursosActionPerformed

    private void btnCancelarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarCursoActionPerformed
        desactivarBotonesCurso();
    }//GEN-LAST:event_btnCancelarCursoActionPerformed

    private void btnListarCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarCursosActionPerformed
        listarCursos();
    }//GEN-LAST:event_btnListarCursosActionPerformed

    private void tblCursosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCursosMouseClicked
        int pos = tblCursos.getSelectedRow();
        
        int codigo = (Integer) tblCursos.getValueAt(pos, 0);
        
        editarCurso = controladorCurso.read(new Curso(codigo, "", 0, null));
        
        activarBotonesCurso();
    }//GEN-LAST:event_tblCursosMouseClicked

    private void btnActualizarCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarCursosActionPerformed
        pantallaEditarCurso = new PantallaEditarCurso(editarCurso);
        pantallaEditarCurso.setVisible(true);
        tblCursos.clearSelection();
        desactivarBotonesCurso();
    }//GEN-LAST:event_btnActualizarCursosActionPerformed

    public void listarCursos(){
        List<Curso> lista = controladorCurso.findAll();
        System.out.println(lista);
        
        DefaultTableModel modelo = (DefaultTableModel) tblCursos.getModel();
        
        modelo.setRowCount(0);
        for (Curso curso : lista) {
            Object[] rowData = {curso.getCodigo(), curso.getCurso().trim(), curso.getAlumnos(), curso.getDocente().getCedula().trim()};
            modelo.addRow(rowData);
        }
    }
    
    public void listarDocentes(){
        List<Persona> lista = controladorPersona.findAll();
        
        DefaultTableModel modelo = (DefaultTableModel) tblDocente.getModel();
        
        modelo.setRowCount(0);
        for (Persona persona : lista) {
            if(persona.getRol().equals("Docente")){
                Object[] rowData = {persona.getRol().trim(), persona.getNombre().trim(), persona.getApellido().trim(), persona.getCedula().trim()};
                modelo.addRow(rowData);
            }
        }
        tblDocente.setModel(modelo);
    }
    
    public void cargarDatos(){
        txtCedula.setText(rector.getCedula().trim());
        txtDirector.setText(rector.getNombre().trim()+" "+rector.getApellido().trim());
    }

    public void limpiar(){
        txtCedula.setText("");
        txtDirector.setText("");
        
        DefaultTableModel modelo = (DefaultTableModel) tblDocente.getModel();
        modelo.setRowCount(0);
        for (int i = 0; i < modelo.getRowCount(); i++) {
            modelo.removeRow(i);
        }
        
        DefaultTableModel modelo2 = (DefaultTableModel) tblCursos.getModel();
        modelo2.setRowCount(0);
        for (int i = 0; i < modelo.getRowCount(); i++) {
            modelo2.removeRow(i);
        }
    }
    
    public void activarBotonesDocente(){
        btnActualizarDocente.setEnabled(true);
        btnCancelarDocente.setEnabled(true);
    }
    
    public void desactivarBotonesDocente(){
        btnActualizarDocente.setEnabled(false);
        btnCancelarDocente.setEnabled(false);
    }
    
    public void activarBotonesCurso(){
        btnActualizarCursos.setEnabled(true);
        btnCancelarCurso.setEnabled(true);
    }
    
    public void desactivarBotonesCurso(){
        btnActualizarCursos.setEnabled(false);
        btnCancelarCurso.setEnabled(false);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarCursos;
    private javax.swing.JButton btnActualizarDocente;
    private javax.swing.JButton btnCancelarCurso;
    private javax.swing.JButton btnCancelarDocente;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnCrearCursos;
    private javax.swing.JButton btnCrearDocente;
    private javax.swing.JButton btnListarCursos;
    private javax.swing.JButton btnListarDocentes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblCursos;
    private javax.swing.JTable tblDocente;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtDirector;
    // End of variables declaration//GEN-END:variables
}
