/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista;

import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import ec.edu.ups.controlador.ControladorContratos;
import ec.edu.ups.controlador.ControladorMovimientoVehiculo;
import ec.edu.ups.controlador.ControladorParqueadero;
import ec.edu.ups.controlador.ControladorVehiculo;
import ec.edu.ups.controlador.FabricaDeVehiculos;
import ec.edu.ups.imagen.ControladorImagenes;
import ec.edu.ups.modelo.ContratoBD;
import ec.edu.ups.modelo.ParqueaderoBD;
import ec.edu.ups.modelo.PersonaBD;
import ec.edu.ups.modelo.VehiculoBD;
import ec.edu.ups.modelo.VehiculosParqueadero;
import java.awt.Color;
import java.awt.Image;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.border.LineBorder;

/**
 *
 * @author Estudiantes
 */
public class PantallaVehiculos extends javax.swing.JFrame {

    PersonaBD personaBD;
    PanrallaRegistrarPersona panrallaRegistrarPersona;
    PantallaRegistroVehiculo pantallaRegistroVehiculo;
    PantallaContratos pantallaContratos;
   
    int contadorr=0;

    ControladorImagenes controladorImagenes;
    
    ControladorContratos controladorContratos;
    
    ControladorVehiculo controladorVehiculo;
    
    ControladorParqueadero controladorParqueadero;
    
    ControladorMovimientoVehiculo controladorMovimientoVehiculo;
    
    VehiculoBD vehiculoPasar;
    
    boolean pagar = true;
    /**
     * Creates new form PantallaVehiculos
     */
    public PantallaVehiculos(PersonaBD persona) {
        initComponents();
        this.setLocationRelativeTo(null);
        
        controladorVehiculo = new ControladorVehiculo();
        
        controladorContratos = ControladorContratos.getInstance();
        
        controladorImagenes = new ControladorImagenes();
        
        controladorParqueadero = new ControladorParqueadero();
        
        personaBD = persona;
     
        
        btnComprobate.setEnabled(false);
        if(personaBD.getRol().equals("Usuario")){
            menuUsuario.setVisible(false);
            menuContrato.setVisible(false);
        }else{
            menuUsuario.setVisible(true);
            menuContrato.setVisible(true);
        }
        
        crearParqueadero();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtBuscarVehiculo = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtPlaca = new javax.swing.JTextField();
        txtModelo = new javax.swing.JTextField();
        txtPropietario = new javax.swing.JTextField();
        txtPuesto = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtHoraEntrada = new javax.swing.JTextField();
        lblHoraSalida = new javax.swing.JLabel();
        lblFechaSalida = new javax.swing.JLabel();
        txtHoraSalida = new javax.swing.JTextField();
        calendarSalida = new com.toedter.calendar.JDateChooser();
        jLabel13 = new javax.swing.JLabel();
        cbxAccion = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        cbxEntrada = new javax.swing.JComboBox<>();
        btnComprobate = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        txtMinutosSalida = new javax.swing.JTextField();
        pnlParqueadero = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuClientes = new javax.swing.JMenuItem();
        menuUsuario = new javax.swing.JMenuItem();
        menuContrato = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagen/cuenca.PNG"))); // NOI18N
        jLabel2.setText("jLabel2");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel12.setText("PARQUADERO");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagen/OtroEmovPeroChikitoYAzul.PNG"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(163, 163, 163)
                .addComponent(jLabel1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel12)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel3.setText("Vehiculo:");

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagen/buscar.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jLabel4.setText("Placa:");

        jLabel5.setText("Modelo:");

        jLabel6.setText("Propietario:");

        jLabel7.setText("Puesto:");

        jLabel8.setText("Entrada:");

        txtPlaca.setEditable(false);

        txtModelo.setEditable(false);

        txtPropietario.setEditable(false);

        jLabel9.setText("Fecha de entrada:");

        txtHoraEntrada.setEditable(false);

        lblHoraSalida.setText("Hora Salida:");

        lblFechaSalida.setText("Fecha Salida:");

        calendarSalida.setDateFormatString("dd/MM/yyyy");
        calendarSalida.setEnabled(false);

        jLabel13.setText("Accion:");

        cbxAccion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elegir", "Ingresar", "Retirar" }));
        cbxAccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxAccionActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagen/aceptar (3).png"))); // NOI18N
        jButton2.setText("Aceptar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagen/escoba.png"))); // NOI18N
        jButton3.setText("Limpiar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        cbxEntrada.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elegir", "Normal", "Contrato" }));
        cbxEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxEntradaActionPerformed(evt);
            }
        });

        btnComprobate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagen/aceptar (3).png"))); // NOI18N
        btnComprobate.setText("Comprobar");
        btnComprobate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprobateActionPerformed(evt);
            }
        });

        jLabel14.setText(":");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPlaca))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtModelo)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(cbxAccion, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtBuscarVehiculo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuscar))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblHoraSalida)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtHoraSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMinutosSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblFechaSalida)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(calendarSalida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtHoraEntrada))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(cbxEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnComprobate)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtPropietario)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPuesto))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(cbxAccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBuscarVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6))
                    .addComponent(txtPropietario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(btnComprobate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtHoraEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHoraSalida)
                    .addComponent(txtHoraSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(txtMinutosSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(calendarSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFechaSalida))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(16, 16, 16))
        );

        pnlParqueadero.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout pnlParqueaderoLayout = new javax.swing.GroupLayout(pnlParqueadero);
        pnlParqueadero.setLayout(pnlParqueaderoLayout);
        pnlParqueaderoLayout.setHorizontalGroup(
            pnlParqueaderoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 766, Short.MAX_VALUE)
        );
        pnlParqueaderoLayout.setVerticalGroup(
            pnlParqueaderoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 638, Short.MAX_VALUE)
        );

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagen/barrera-de-estacionamiento.png"))); // NOI18N

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagen/barrera-de-estacionamiento.png"))); // NOI18N

        jButton1.setText("Actualizar VIsta");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagen/logout.png"))); // NOI18N
        jButton5.setText("Cerrar sesion");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jMenu1.setText("Gestion Personas");

        menuClientes.setText("Gestion Clientes");
        menuClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuClientesActionPerformed(evt);
            }
        });
        jMenu1.add(menuClientes);

        menuUsuario.setText("Gestion Usuarios");
        menuUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuUsuarioActionPerformed(evt);
            }
        });
        jMenu1.add(menuUsuario);

        menuContrato.setText("Contratos");
        menuContrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuContratoActionPerformed(evt);
            }
        });
        jMenu1.add(menuContrato);

        jMenuBar1.add(jMenu1);

        jMenu2.setText(" Gestion Vehiculos");

        jMenuItem4.setText("Vehiculos");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11))
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlParqueadero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel11))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton5))))
                    .addComponent(pnlParqueadero, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuUsuarioActionPerformed
        panrallaRegistrarPersona = new PanrallaRegistrarPersona("Usuario");
        panrallaRegistrarPersona.setVisible(true);
    }//GEN-LAST:event_menuUsuarioActionPerformed

    private void menuClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuClientesActionPerformed
        panrallaRegistrarPersona = new PanrallaRegistrarPersona("Clientes");
        panrallaRegistrarPersona.setVisible(true);
    }//GEN-LAST:event_menuClientesActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        pantallaRegistroVehiculo = new PantallaRegistroVehiculo();
        pantallaRegistroVehiculo.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void cbxAccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxAccionActionPerformed
        String opcion = cbxAccion.getSelectedItem()+"";
        if(opcion.equals("Ingresar")){
            lblFechaSalida.setVisible(false);
            lblHoraSalida.setVisible(false);
            txtHoraSalida.setVisible(false);
            calendarSalida.setVisible(false);
            txtMinutosSalida.setVisible(false);
        }else{
            lblFechaSalida.setVisible(true);
            lblHoraSalida.setVisible(true);
            txtHoraSalida.setVisible(true);
            calendarSalida.setVisible(true);
            txtMinutosSalida.setVisible(true);

        }
    }//GEN-LAST:event_cbxAccionActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String placa = txtBuscarVehiculo.getText();
        
        if(placa.isEmpty()){
            JOptionPane.showMessageDialog(this, "Llene el campo de busqueda");
        }else{
            
            VehiculoBD v = controladorVehiculo.buscarPlaca(placa);
            if(v!=null){
                txtPlaca.setText(placa);
                txtModelo.setText(v.getModelo());
                txtPropietario.setText(v.getPersona().getCedula());
                vehiculoPasar = v;
                txtHoraEntrada.setText(new Date()+"");
            }
            if(cbxAccion.getSelectedItem().equals("Retirar")){
            List<ParqueaderoBD> lista = controladorParqueadero.findAll();
            ParqueaderoBD p = null;
            
                for (ParqueaderoBD pa : lista) {
                    System.out.println(pa);
                    if(pa.getVehiculo().equals(vehiculoPasar) && pa.getTipo().equals("Parqueado")){
                        p = pa;
                        vehiculoPasar = v;
                    }
                }
                if(p!=null){
                    txtHoraEntrada.setText(p.getIngreso()+"");
                    txtPuesto.setText(p.getPuesto()+"");
                }
            }
        }
        
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void cbxEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxEntradaActionPerformed
        String com = cbxEntrada.getSelectedItem()+"";
        if(com.equals("Contrato")){
            btnComprobate.setEnabled(true);
        }else{
            pagar = true;
            btnComprobate.setEnabled(false);
            
        }
    }//GEN-LAST:event_cbxEntradaActionPerformed

    private void menuContratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuContratoActionPerformed
        pantallaContratos = new PantallaContratos();
        pantallaContratos.setVisible(true);
        crearParqueadero();
    }//GEN-LAST:event_menuContratoActionPerformed

    private void btnComprobateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprobateActionPerformed
        PersonaBD p = vehiculoPasar.getPersona();
        
        ContratoBD c = controladorContratos.buscarCedula(p.getCedula());
        if(c!=null){
            Date f = new Date();
            int fechaIni = f.compareTo(c.getInicio());
            int fechaInf = f.compareTo(c.getSalida());
            if( (fechaIni>=0 && fechaInf<=0)){
                JOptionPane.showMessageDialog(this, "La presona si cuenta con un contrato");
                pagar = false;
                txtPuesto.setText(c.getPuesto()+"");
            }else{
                JOptionPane.showMessageDialog(this, "Su contrato esta fuera de fecha o caducado");
            }
        }else{
            JOptionPane.showMessageDialog(this, "La persona dueña del vehiculo no tiene contrato");
        }
    }//GEN-LAST:event_btnComprobateActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(cbxAccion.getSelectedItem().equals("Ingresar")){            
            List<ParqueaderoBD> lista = controladorParqueadero.findAll();
            boolean aaaa = false;
            int puesto = Integer.parseInt(txtPuesto.getText());
            for (ParqueaderoBD parqueaderoBD : lista) {
                if(parqueaderoBD.getPuesto()==puesto && !parqueaderoBD.getTipo().equals("Retirado")){
                    aaaa = true;
                }
            }
            
            if(aaaa == false ){
                Date fecha = new Date();
                    
                ParqueaderoBD p = new ParqueaderoBD();
                p.setIngreso(fecha);
                p.setPuesto(puesto);
                if (pagar != true) {
                    p.setTipo("Parqueado");
                } else {
                    p.setTipo("Parqueado");
                }
                p.setVehiculo(vehiculoPasar);
                boolean a = controladorParqueadero.create(p);
                if (a != false) {
                    comprobante(p);
                    JOptionPane.showMessageDialog(this, "El vehiculo se a agregado conrrectamente");
                    limpiar();
                    controladorMovimientoVehiculo = new ControladorMovimientoVehiculo(pnlParqueadero, "Ingresar", p.getPuesto());
                } else {
                    JOptionPane.showMessageDialog(this, "Error en el ingreso del vehiculo");
                }
            }else{
                JOptionPane.showMessageDialog(this, "Puesto ya ocupado");
            }
        }else if(cbxAccion.getSelectedItem().equals("Retirar")){
            Date salida = calendarSalida.getDate();
            int hora = Integer.parseInt(txtHoraSalida.getText());
            int minutos = Integer.parseInt(txtMinutosSalida.getText());
            salida.setMinutes(minutos-1);
            salida.setHours(hora-1);
            List<ParqueaderoBD> lista = controladorParqueadero.findAll();
            
            ParqueaderoBD p = null;
            int puesto = Integer.parseInt(txtPuesto.getText());
            for (ParqueaderoBD parqueaderoBD : lista) {
                if(parqueaderoBD.getPuesto()==puesto && parqueaderoBD.getTipo().equals("Parqueado")){
                   
                    p=parqueaderoBD;
                }
            }
            if(p!=null){
                if(pagar != true){
                    ContratoBD co = controladorContratos.buscarCedula(p.getVehiculo().getPersona().getCedula());
                    if(co.isPagado()==false){
                        JOptionPane.showMessageDialog(this, "Usted cuenta con un saldo pendiente  de: "+co.getValor());
                    }else{
                        p.setTotal(co.getValor());
                        JOptionPane.showMessageDialog(this, "El valor de "+co.getValor()+" ya  fue cancelado");
                    }
                }else{
                    double a = calcularPago(new Date(), salida);
                    p.setTotal(a);
                    JOptionPane.showMessageDialog(this, "El valor a pagar es de "+ a);
                }
                p.setSalida(salida);
                p.setTipo("Retirado");
                controladorParqueadero.update(p);
                comprobante(p);
                limpiar();
                controladorMovimientoVehiculo= new ControladorMovimientoVehiculo(pnlParqueadero, "Retirar", p.getPuesto());
            }else{
                JOptionPane.showMessageDialog(this, "El vehiculo no se encuentra estacionado");
            }
            
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        pnlParqueadero.removeAll();
        pnlParqueadero.updateUI();
        System.out.println("a");
        crearParqueadero();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        this.dispose();
        PantallaPrincipal pantallaPrincipal = new PantallaPrincipal();
        pantallaPrincipal.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        limpiar();
    }//GEN-LAST:event_jButton3ActionPerformed

    public void crearParqueadero(){
        /*JLabel lb = new JLabel();
        lb.setBounds(150, 140, 50, 40);
        lb.setIcon(controladorImagenes.asignarResrado());
        lb.setText("A");
        lb.setVisible(true);
        pnlParqueadero.add(lb);
        setVisible(true);
        */
        System.out.println("aa");
        pnlParqueadero.removeAll();
        pnlParqueadero.updateUI();
        
        List<ParqueaderoBD> parqueadero = controladorParqueadero.findAll();
        List<ContratoBD> contratos = controladorContratos.findAll();
        int cont = 1;
        int x = 64;
        int y = 0;
        
        JLabel lb;
        
        for (int i = 0; i < 5; i++) {
            for (int j = 0; j < 10; j++) {
                VehiculosParqueadero v = null;
                boolean cent = false;
                
                for (ContratoBD contrato : contratos) {
                    
                    if(contrato.getPuesto()==cont ){
                        Date f = new Date();
                        int fechaIni = f.compareTo(contrato.getInicio());
                        int fechaInf = f.compareTo(contrato.getSalida());
                        
                        if( (fechaIni>=0 && fechaInf<=0)){
                            v = FabricaDeVehiculos.crearVehiculos(contrato.getPuesto(), "Reservado");
                            cent = true;
                        }
                    }
                }
                
                for (ParqueaderoBD parque : parqueadero) {
                    if(parque.getPuesto()==cont && !parque.getTipo().equals("Vacio") && !parque.getTipo().equals("Retirado")){
                        v = FabricaDeVehiculos.crearVehiculos(parque.getPuesto(), parque.getTipo());
                        cent= true;
                    }
                }

                lb = new JLabel();
                
                if(cent==true){
                    //v = FabricaDeVehiculos.crearVehiculos(cont, "Vacio");
                    lb.setIcon(v.getImage());
                }
                
                lb.setBounds(x, y, 64, 64);
                lb.setVisible(true);
                lb.setBorder(new LineBorder(Color.BLACK));
                lb.setText(cont+"");
                pnlParqueadero.add(lb);
                x+=64;
                cont++;
            }
            x=64;
            y+=128;
        }
        pnlParqueadero.updateUI();
    }
    
    public double calcularPago(Date f, Date f2){
        int añoIngreso = f.getYear()*525600;
        int mesIngreso = f.getMonth()*43800;
        int diaIngreso = f.getDay()*1440;
        int horaIngreso = f.getHours()*60;
        int minutoIngreso = f.getMinutes();

        int añoSalida = f2.getYear()*525600;
        int mesSalida = f2.getMonth()*43800;
        int diaSalida = f2.getDay()*1440;
        int horaSalida = f2.getHours()*60;
        int minutoSalida = f2.getMinutes();

        int totalIngreso= añoIngreso+mesIngreso+diaIngreso+horaIngreso+minutoIngreso;
        int totalSalida= añoSalida+mesSalida+diaSalida+horaSalida+minutoSalida;

        int totalTotal = totalSalida-totalIngreso;
        int fracciones = (int) totalTotal/10;

        fracciones++;
        
        double total = Math.abs(fracciones*0.20);
        return total;
    }
    
    public void comprobante(ParqueaderoBD p){
        Document documento = new Document();
        try {
            try {
                PdfWriter.getInstance(documento, new FileOutputStream("factura "+contadorr+".pdf"));
                documento.open();
                documento.add(new Paragraph("--------------------------------------------"));
                documento.add(new Paragraph("                COMPROBANTE                 "));
                documento.add(new Paragraph("--------------------------------------------"));
                documento.add(new Paragraph("Cliente: "+p.getVehiculo().getPersona().getNombre()+" "+p.getVehiculo().getPersona().getApellido()));
                documento.add(new Paragraph("Placa del vehiculo: "+p.getVehiculo().getPlaca()));
                documento.add(new Paragraph("Fecha de entrada: "+p.getIngreso()));
                documento.add(new Paragraph("Fecha de salida: "+p.getSalida()));
                documento.add(new Paragraph("--------------------------------------------"));
                documento.add(new Paragraph("Total: "+p.getTotal()));
                
            } catch (FileNotFoundException ex) {
                Logger.getLogger(PantallaVehiculos.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (DocumentException ex) {
            Logger.getLogger(PantallaVehiculos.class.getName()).log(Level.SEVERE, null, ex);
        }
        documento.close();
        contadorr++;
    }
    
    public void limpiar(){
        txtBuscarVehiculo.setText("");
        txtHoraEntrada.setText("");
        txtHoraSalida.setText("");
        txtMinutosSalida.setText("");
        txtModelo.setText("");
        txtPlaca.setText("");
        txtPropietario.setText("");
        txtPuesto.setText("");
        calendarSalida.setDate(new Date());
   }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnComprobate;
    private com.toedter.calendar.JDateChooser calendarSalida;
    private javax.swing.JComboBox<String> cbxAccion;
    private javax.swing.JComboBox<String> cbxEntrada;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblFechaSalida;
    private javax.swing.JLabel lblHoraSalida;
    private javax.swing.JMenuItem menuClientes;
    private javax.swing.JMenuItem menuContrato;
    private javax.swing.JMenuItem menuUsuario;
    private javax.swing.JPanel pnlParqueadero;
    private javax.swing.JTextField txtBuscarVehiculo;
    private javax.swing.JTextField txtHoraEntrada;
    private javax.swing.JTextField txtHoraSalida;
    private javax.swing.JTextField txtMinutosSalida;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtPlaca;
    private javax.swing.JTextField txtPropietario;
    private javax.swing.JTextField txtPuesto;
    // End of variables declaration//GEN-END:variables
}
